### ISSUE TITLE
error. again

### ISSUE THREAD

**Issue by kingofkingzcd** [MrEvilGamer/qb-weedpicking#10]
![image](https://user-images.githubusercontent.com/83891867/160621583-990074cb-375f-4c2d-bd67-6a5433906233.png)

this is like the 4th time ive downloaded and attempted use. every time out of the box there are errors that break the script. seems like a very cool aspect and hope it is resolved soon

**Comment by kingofkingzcd** [comment]
![image](https://user-images.githubusercontent.com/83891867/160622646-7628dbca-7a48-4ae7-9755-82e1937bb093.png)
 heres the fix

**Comment by MrEvilGamer** [comment]
fixed :)
