### ISSUE TITLE
problems to spawn object visible

### ISSUE THREAD

**Issue by Cyberstudios2020** [MrEvilGamer/qb-weedpicking#6]
Hi MrEvilGamer, i do all what you say in your Readme, but i have one Problem i dont get the Items to Spwan. So i add the lines in the qb-core/client/function how you and restart the server but nothing comes to spawn we find with luck the Text where stand pick up but no items, i try also other objects but nothings help

at the picture you see what i mean ;)

https://gyazo.com/b3d3fe4e9d5147ea23a607ea2e8edb9b

can you try to help me?

thanks

**Comment by MrEvilGamer** [comment]
Error?

**Comment by Cyberstudios2020** [comment]
i get no error in the live console 

[    c-scripting-core] Creating script environments for qb-weedpicking
[ citizen-server-impl] Started resource qb-weedpicking

and no error by picking up the stuff

**Comment by MrEvilGamer** [comment]
Any error in f8 console?

**Comment by Cyberstudios2020** [comment]
No Error that speak from the weedpicking, only from anticheat and a qb-core:nui Error that looks like This

https://gyazo.com/882e994a52c4a9db0e487d6890037520

**Comment by MrEvilGamer** [comment]
did you read the readme?

**Comment by Cyberstudios2020** [comment]
Yes I import all line at the position where you say, and i try a other write for the function but nothing change the Problem, there spawn nothing.

your first part i have import:

https://gyazo.com/4cf992f64bdfe242a126d0e11e44f85e

The three last parts i Importet:

https://gyazo.com/2c5f33b967562ca491d206072564d5f7

**Comment by MattiVboiii** [comment]
I have the same problem... On the previous core it works all fine, but the new one is not working...

**Comment by MrEvilGamer** [comment]
For now i bugged the script i'll fix it soon

**Comment by MrEvilGamer** [comment]
The issue is fixed thanks for letting know :)

**Comment by Pistolion** [comment]
Where can i find the updated weedpicking.lua mine is giving errors?
